id: A16776CE7
title: Prayer to Invoke the Wisdom Mind of the Gentle Protector Sakya Paṇḍita
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:27:20.979554
  last_modified_at: 2022-03-01 01:27:20.979562
