id: A16776CE7
title: Verses of Aspiration to Recite While Prostrating
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:27:20.985710
  last_modified_at: 2022-03-01 01:27:20.985713
